FORMAT: 1A
HOST: https://kubehosting.apiblueprint.org/

# kubehosting

KubeHosting API documentation

## Registration [/signup]
### Register a new user [POST]

+ Request (application/json)

        {
            "email": "example@example.com",
            "password": "supersecret"
        }
+ Response 200

## Login [/login]
### Login [POST]

+ Request (application/json)

        {
            "email": "example@example.com",
            "password": "supersecret"
        }
+ Response 200
+ Response 400

## Logout [/logout]
### Logout [POST]

+ Request ()
+ Respose 200

## User's services [/user/{userID}/services/{serviceID}]
### Get user's services [GET]
+ Parameters
    + userID (uuid) - ID of the user
+ Request (application/json)
        
        {
            "name": "my-blog",
            "config": ".yaml file"
        }
+ Response 200 (application/json)

        {
            [{
                "name": "my-blog", 
                "config: ".yaml file"
            }]
        }

### Create a service [POST]
+ Parameters
    + userID (uuid) - ID of the user
+ Request (application/json)
        
        {
            "name": "my-blog",
            "config": ".yaml file"
        }
+ Response 200

### Edit a service [PUT]
+ Parameters
    + userID (uuid) - ID of the user
    + serviceID (uuid) - ID of the service
+ Request (application/json)
        
        {
            "name": "my-blog",
            "config": ".yaml file"
        }
+ Response 200

### Delete a service [DELETE]
+ Parameters
    + userID (uuid) - ID of the user
    + serviceID (uuid) - ID of the service
+ Request ()
+ Response 200

## Start a service [/users/{userID}/services/{serviceID}/start]
### Start [POST]
+ Parameters
    + userID (uuid) - ID of the user
    + serviceID (uuid) - ID of the service
+ Request ()
+ Response 200

## Stop a service [/users/{userID}/services/{serviceID}/stop]
### Stop [POST]
+ Parameters
    + userID (uuid) - ID of the user
    + serviceID (uuid) - ID of the service
+ Request ()
+ Response 200