FORMAT: 1A
HOST: https://kubehosting.apiblueprint.org/

# kubehosting

KubeHosting API documentation

## User collection [/user]

### Create a New User [POST]
Add a new user to the list of registered users. It takes a JSON object
containing the user's email address and its password.

+ Request (application/json)

        {
            "email": "me@example.com",
            "password": "Ar4nd0mP4ssw0rD"
        }

+ Response 200 (application/json)

        {}

+ Response 400 (application/json)

        {
            "error_msg": "Password is too short",
            "reason": "password: 123"
        }