apiVersion: v1
clusters:
- cluster:
    certificate-authority: /kubehosting/config/kube/ca.crt
    extensions:
    - extension:
        last-update: Thu, 26 May 2022 17:09:55 CEST
        provider: minikube.sigs.k8s.io
        version: v1.25.2
      name: cluster_info
    server: https://192.168.49.2:8443
  name: minikube
contexts:
- context:
    cluster: minikube
    extensions:
    - extension:
        last-update: Thu, 26 May 2022 17:09:55 CEST
        provider: minikube.sigs.k8s.io
        version: v1.25.2
      name: context_info
    namespace: default
    user: minikube
  name: minikube
current-context: minikube
kind: Config
preferences: {}
users:
- name: admin
  user:
    password: uXFGweU9l34qcif
    username: admin
- name: cluster-admin
  user:
    password: uXFGweU9l34qcif
    username: admin
- name: minikube
  user:
    client-certificate: /kubehosting/config/kube/client.crt
    client-key: /kubehosting/config/kube/client.key
