name: kubehosting-CI
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the stack
      run: docker-compose up -d
    - name: Test
      run: docker-compose exec node npm test