name: kubehosting-CI
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run tests
      run: |
        docker network create minikube
        docker-compose -f docker-compose.yml -f docker-compose.tests.yml up -T
